version: '3.8'  # Use a newer version here if necessary
services:
  order-service:
    build: ./order-service
    ports:
      - "5000:5000"
  product-service:
    build: ./product-service
    ports:
      - "5001:5000"
  user-service:
    build: ./user-service
    ports:
      - "5002:5000"
